#ifndef _EXCEPTIONS_H
#define _EXCEPTIONS_H

#define TIMEOUT_EXCEPTION			1
#define PACKET_TOO_SMALL_EXCEPTION	2
#define GOTO_IDLE_EXCEPTION			3
#define GOTO_RESET_EXCEPTION		4
#define COMM_READ_EXCEPTION			5

#endif
