// _KeyInformation_EOArchive_English.java
// Generated by EnterpriseObjects palette at Sunday, 19 June 2005 20:24:23 Asia/Seoul

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _KeyInformation_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    com.webobjects.eointerface.swing.EOFrame _eoFrame0;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0, _nsImageView1, _nsImageView2;
    com.webobjects.eointerface.swing.EOTable _nsTableView0, _nsTableView1, _nsTableView2;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1, _eoTableColumn2, _eoTableColumn3;
    com.webobjects.eointerface.swing.EOTextField _eoTextField0, _eoTextField1, _eoTextField2, _eoTextField3, _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField16, _nsTextField17, _nsTextField18, _nsTextField19, _nsTextField2, _nsTextField20, _nsTextField21, _nsTextField22, _nsTextField23, _nsTextField24, _nsTextField25, _nsTextField26, _nsTextField27, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsBox6, _nsBox7, _nsBox8, _nsBox9, _nsCustomView0, _nsCustomView1, _nsSplitView0, _nsView0, _nsView1, _nsView2, _nsView3;
    com.webobjects.foundation.NSTimestampFormatter _nsTimestampFormatter0, _nsTimestampFormatter1, _nsTimestampFormatter2, _nsTimestampFormatter3;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton10, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8, _nsButton9;
    javax.swing.JCheckBox _nsButton11;
    javax.swing.JComboBox _popup0;
    javax.swing.JPanel _nsView4;
    javax.swing.JTabbedPane _nsTabView0;

    public _KeyInformation_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _eoTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTimestampFormatter3 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%e %B %Y"), "");
        _eoTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTimestampFormatter2 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%e %B %Y"), "");
        _nsTimestampFormatter1 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%e %B %Y"), "");
        _eoTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _eoTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        _nsTimestampFormatter0 = (com.webobjects.foundation.NSTimestampFormatter)_registered(new com.webobjects.foundation.NSTimestampFormatter("%e %B %Y"), "");
        _nsView3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsTextField27 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField14");
        _nsTextField26 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField13");
        _nsTextField25 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        _nsTextField24 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField23 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsBox9 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox8 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _nsView2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsSplitView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _nsView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox3");
        _nsTextField22 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField13");
        _nsTextField21 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        _nsTextField20 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField19 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox2");
        _nsTextField18 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox1");
        _nsTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "expiredIcon")) != null)) {
            _nsImageView2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOImageView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsImageView2");
        } else {
            _nsImageView2 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "photoIDthumbnail")) != null)) {
            _nsImageView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOImageView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsImageView1");
        } else {
            _nsImageView1 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "photoIDfullsize")) != null)) {
            _nsImageView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOImageView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsImageView0");
        } else {
            _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "subkeyType")) != null)) {
            _nsTextField15 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField15");
        } else {
            _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField15");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "subkeyStrength")) != null)) {
            _nsTextField14 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField14");
        } else {
            _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField151");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "subkeyExpires")) != null)) {
            _nsTextField13 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField13");
        } else {
            _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField153");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "subkeyCreated")) != null)) {
            _nsTextField12 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField12");
        } else {
            _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField152");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "revokeSignature")) != null)) {
            _nsButton10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton10");
        } else {
            _nsButton10 = (javax.swing.JButton)_registered(new javax.swing.JButton("Revoke"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "removeUserID")) != null)) {
            _nsButton9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton9");
        } else {
            _nsButton9 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton31");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "removeSignature")) != null)) {
            _nsButton8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton8");
        } else {
            _nsButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton311");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "addSignature")) != null)) {
            _nsButton7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton7");
        } else {
            _nsButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton32");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "makePrimaryID")) != null)) {
            _nsButton6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton6");
        } else {
            _nsButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("Primary"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "addUserID")) != null)) {
            _nsButton5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton5");
        } else {
            _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton3");
        }

        _eoTableColumn3 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "userIDs")) != null)) {
            _nsTableView2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView2");
        } else {
            _nsTableView2 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        _eoTableColumn2 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn1");
        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "signatures")) != null)) {
            _nsTableView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView1");
        } else {
            _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "type")) != null)) {
            _nsTextField11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField11");
        } else {
            _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField16");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "strength")) != null)) {
            _nsTextField10 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField10");
        } else {
            _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField15");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "keyID")) != null)) {
            _nsTextField9 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField9");
        } else {
            _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField14");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "email")) != null)) {
            _nsTextField8 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField8");
        } else {
            _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField14");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "expires")) != null)) {
            _nsTextField7 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField7");
        } else {
            _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField13");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "created")) != null)) {
            _nsTextField6 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField6");
        } else {
            _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "comment")) != null)) {
            _nsTextField5 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField5");
        } else {
            _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField15");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "fingerprint")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField17");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "subkeyStatus")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField154");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "changeSubkeyExpiryDate")) != null)) {
            _nsButton4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton4");
        } else {
            _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton("Change Expiry Date"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "removeSubkey")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton311");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "addSubkey")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "NSButton32");
        }

        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "subkeys")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "revokeSubkey")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Revoke"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "changePassphrase")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("Change Passphrase"), "NSButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "trust")) != null)) {
            _popup0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JComboBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_popup0");
        } else {
            _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "disabled")) != null)) {
            _nsButton11 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton11");
        } else {
            _nsButton11 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Disable"), "NSButton4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "name")) != null)) {
            _nsTextField2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField2");
        } else {
            _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField13");
        }

        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField12");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        _nsView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tabs")) != null)) {
            _nsTabView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JTabbedPane)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTabView0");
        } else {
            _nsTabView0 = (javax.swing.JTabbedPane)_registered(new javax.swing.JTabbedPane(), "NSTabView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "window")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Window");
        }

        _nsView4 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_eoFrame0, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsImageView2") == null) {
            _connect(_owner(), _nsImageView2, "expiredIcon");
        }

        if (_replacedObjects.objectForKey("_nsImageView1") == null) {
            _connect(_owner(), _nsImageView1, "photoIDthumbnail");
        }

        if (_replacedObjects.objectForKey("_nsImageView0") == null) {
            _connect(_owner(), _nsImageView0, "photoIDfullsize");
        }

        if (_replacedObjects.objectForKey("_nsTextField15") == null) {
            _connect(_owner(), _nsTextField15, "subkeyType");
        }

        if (_replacedObjects.objectForKey("_nsTextField14") == null) {
            _connect(_owner(), _nsTextField14, "subkeyStrength");
        }

        if (_replacedObjects.objectForKey("_nsTextField13") == null) {
            _connect(_owner(), _nsTextField13, "subkeyExpires");
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _connect(_owner(), _nsTextField12, "subkeyCreated");
        }

        _nsButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "revokeSignature", _nsButton10), ""));

        if (_replacedObjects.objectForKey("_nsButton10") == null) {
            _connect(_owner(), _nsButton10, "revokeSignature");
        }

        _nsButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "removeUserID", _nsButton9), ""));

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _connect(_owner(), _nsButton9, "removeUserID");
        }

        _nsButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "removeSignature", _nsButton8), ""));

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _connect(_owner(), _nsButton8, "removeSignature");
        }

        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "addSignature", _nsButton7), ""));

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _connect(_owner(), _nsButton7, "addSignature");
        }

        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "makePrimaryID", _nsButton6), ""));

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _connect(_owner(), _nsButton6, "makePrimaryID");
        }

        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "addUserID", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _connect(_owner(), _nsButton5, "addUserID");
        }

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _connect(_nsTableView2, _owner(), "dataSource");
        }

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _connect(_owner(), _nsTableView2, "userIDs");
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_nsTableView1, _owner(), "dataSource");
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _connect(_owner(), _nsTableView1, "signatures");
        }

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _connect(_owner(), _nsTextField11, "type");
        }

        if (_replacedObjects.objectForKey("_nsTextField10") == null) {
            _connect(_owner(), _nsTextField10, "strength");
        }

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _connect(_owner(), _nsTextField9, "keyID");
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _connect(_owner(), _nsTextField8, "email");
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _connect(_owner(), _nsTextField7, "expires");
        }

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _connect(_owner(), _nsTextField6, "created");
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _connect(_owner(), _nsTextField5, "comment");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "fingerprint");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "subkeyStatus");
        }

        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changeSubkeyExpiryDate", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _connect(_owner(), _nsButton4, "changeSubkeyExpiryDate");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "removeSubkey", _nsButton3), ""));

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_owner(), _nsButton3, "removeSubkey");
        }

        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "addSubkey", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "addSubkey");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _owner(), "dataSource");
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "subkeys");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "revokeSubkey", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "revokeSubkey");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "changePassphrase", _nsButton0), ""));

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "changePassphrase");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _popup0.setModel(new javax.swing.DefaultComboBoxModel());
            _popup0.addItem("Unknown");
            _popup0.addItem("Undefined");
            _popup0.addItem("Never");
            _popup0.addItem("Marginal");
            _popup0.addItem("Full");
            _popup0.addItem("Ultimate");
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _connect(_owner(), _popup0, "trust");
        }

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _connect(_owner(), _nsButton11, "disabled");
        }

        if (_replacedObjects.objectForKey("_nsTabView0") == null) {
            _connect(_owner(), _nsTabView0, "tabs");
        }

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "window");
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _connect(_owner(), _nsTextField2, "name");
        }
    }

    protected void _init() {
        super._init();
        _setFontForComponent(_eoTextField3, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField2, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField1, "Lucida Grande", 11, Font.PLAIN);
        _setFontForComponent(_eoTextField0, "Lucida Grande", 11, Font.PLAIN);
        if (!(_nsView3.getLayout() instanceof EOViewLayout)) { _nsView3.setLayout(new EOViewLayout()); }
        _nsImageView0.setSize(400, 391);
        _nsImageView0.setLocation(17, 17);
        ((EOViewLayout)_nsView3.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView3.add(_nsImageView0);
        _setFontForComponent(_nsTextField27, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField27.setEditable(false);
        _nsTextField27.setOpaque(false);
        _nsTextField27.setText("Type:");
        _nsTextField27.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField27.setSelectable(false);
        _nsTextField27.setEnabled(true);
        _nsTextField27.setBorder(null);
        _setFontForComponent(_nsTextField26, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField26.setEditable(false);
        _nsTextField26.setOpaque(false);
        _nsTextField26.setText("Status:");
        _nsTextField26.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField26.setSelectable(false);
        _nsTextField26.setEnabled(true);
        _nsTextField26.setBorder(null);
        _setFontForComponent(_nsTextField25, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField25.setEditable(false);
        _nsTextField25.setOpaque(false);
        _nsTextField25.setText("Expires:");
        _nsTextField25.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField25.setSelectable(false);
        _nsTextField25.setEnabled(true);
        _nsTextField25.setBorder(null);
        _setFontForComponent(_nsTextField24, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField24.setEditable(false);
        _nsTextField24.setOpaque(false);
        _nsTextField24.setText("Created:");
        _nsTextField24.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField24.setSelectable(false);
        _nsTextField24.setEnabled(true);
        _nsTextField24.setBorder(null);
        _setFontForComponent(_nsTextField23, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField23.setEditable(false);
        _nsTextField23.setOpaque(false);
        _nsTextField23.setText("Strength:");
        _nsTextField23.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField23.setSelectable(false);
        _nsTextField23.setEnabled(true);
        _nsTextField23.setBorder(null);
        if (!(_nsBox9.getLayout() instanceof EOViewLayout)) { _nsBox9.setLayout(new EOViewLayout()); }
        _nsTextField23.setSize(53, 14);
        _nsTextField23.setLocation(14, 33);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField23, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField23);
        _nsTextField24.setSize(53, 14);
        _nsTextField24.setLocation(14, 55);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField24, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField24);
        _nsTextField25.setSize(53, 14);
        _nsTextField25.setLocation(14, 77);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField25, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField25);
        _nsTextField26.setSize(53, 14);
        _nsTextField26.setLocation(14, 99);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField26, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField26);
        _nsTextField27.setSize(53, 14);
        _nsTextField27.setLocation(14, 11);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField27, EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField27);
        _nsTextField15.setSize(315, 14);
        _nsTextField15.setLocation(69, 11);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField15);
        _nsTextField14.setSize(315, 14);
        _nsTextField14.setLocation(69, 33);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField14);
        _nsTextField12.setSize(315, 14);
        _nsTextField12.setLocation(69, 55);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField12);
        _nsTextField13.setSize(315, 14);
        _nsTextField13.setLocation(69, 77);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField13);
        _nsTextField3.setSize(315, 14);
        _nsTextField3.setLocation(69, 99);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox9.add(_nsTextField3);
        _nsButton4.setSize(124, 22);
        _nsButton4.setLocation(138, 119);
        ((EOViewLayout)_nsBox9.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsBox9.add(_nsButton4);
        if (!(_nsBox8.getLayout() instanceof EOViewLayout)) { _nsBox8.setLayout(new EOViewLayout()); }
        _nsBox9.setSize(396, 149);
        _nsBox9.setLocation(2, 15);
        ((EOViewLayout)_nsBox8.getLayout()).setAutosizingMask(_nsBox9, EOViewLayout.MinYMargin);
        _nsBox8.add(_nsBox9);
        _nsBox8.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Details", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(394, 184);
        _nsTableView0.setLocation(20, 20);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView2.add(_nsTableView0);
        _nsBox8.setSize(400, 166);
        _nsBox8.setLocation(17, 243);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsBox8, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView2.add(_nsBox8);
        _nsButton3.setSize(25, 25);
        _nsButton3.setLocation(37, 210);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton3);
        _nsButton2.setSize(25, 25);
        _nsButton2.setLocation(17, 210);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton2);
        _nsButton1.setSize(73, 22);
        _nsButton1.setLocation(182, 213);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton1);
        if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
        _nsButton8.setSize(25, 25);
        _nsButton8.setLocation(17, 360);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsButton8);
        _nsTableView1.setSize(194, 354);
        _nsTableView1.setLocation(0, 0);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsCustomView1.add(_nsTableView1);
        _nsButton7.setSize(25, 25);
        _nsButton7.setLocation(-3, 360);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsButton7);
        _nsButton10.setSize(73, 22);
        _nsButton10.setLocation(60, 363);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton10, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsButton10);
        if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
        _nsButton5.setSize(25, 25);
        _nsButton5.setLocation(-3, 360);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsButton5);
        _nsButton9.setSize(25, 25);
        _nsButton9.setLocation(17, 360);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton9, EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsButton9);
        _nsTableView2.setSize(194, 354);
        _nsTableView2.setLocation(0, 0);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTableView2, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsCustomView0.add(_nsTableView2);
        _nsButton6.setSize(79, 22);
        _nsButton6.setLocation(58, 363);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsButton6);
        if (!(_nsSplitView0.getLayout() instanceof EOViewLayout)) { _nsSplitView0.setLayout(new EOViewLayout()); }
        _nsCustomView0.setSize(194, 385);
        _nsCustomView0.setLocation(0, 0);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView0.add(_nsCustomView0);
        _nsCustomView1.setSize(194, 385);
        _nsCustomView1.setLocation(203, 0);
        ((EOViewLayout)_nsSplitView0.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsSplitView0.add(_nsCustomView1);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsSplitView0.setSize(397, 385);
        _nsSplitView0.setLocation(20, 20);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsSplitView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView1.add(_nsSplitView0);
        if (!(_nsBox7.getLayout() instanceof EOViewLayout)) { _nsBox7.setLayout(new EOViewLayout()); }
        _nsButton11.setSize(64, 17);
        _nsButton11.setLocation(86, 35);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_nsButton11, EOViewLayout.MinYMargin);
        _nsBox7.add(_nsButton11);
        _popup0.setSize(121, 22);
        _popup0.setLocation(91, 10);
        ((EOViewLayout)_nsBox7.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsBox7.add(_popup0);
        if (!(_nsBox6.getLayout() instanceof EOViewLayout)) { _nsBox6.setLayout(new EOViewLayout()); }
        _nsBox7.setSize(396, 61);
        _nsBox7.setLocation(2, 15);
        ((EOViewLayout)_nsBox6.getLayout()).setAutosizingMask(_nsBox7, EOViewLayout.MinYMargin);
        _nsBox6.add(_nsBox7);
        _nsBox6.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Trust", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField22, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField22.setEditable(false);
        _nsTextField22.setOpaque(false);
        _nsTextField22.setText("Fingerprint:");
        _nsTextField22.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField22.setSelectable(false);
        _nsTextField22.setEnabled(true);
        _nsTextField22.setBorder(null);
        _setFontForComponent(_nsTextField21, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField21.setEditable(false);
        _nsTextField21.setOpaque(false);
        _nsTextField21.setText("Type:");
        _nsTextField21.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField21.setSelectable(false);
        _nsTextField21.setEnabled(true);
        _nsTextField21.setBorder(null);
        _setFontForComponent(_nsTextField20, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField20.setEditable(false);
        _nsTextField20.setOpaque(false);
        _nsTextField20.setText("Strength:");
        _nsTextField20.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField20.setSelectable(false);
        _nsTextField20.setEnabled(true);
        _nsTextField20.setBorder(null);
        _setFontForComponent(_nsTextField19, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField19.setEditable(false);
        _nsTextField19.setOpaque(false);
        _nsTextField19.setText("Key ID:");
        _nsTextField19.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField19.setSelectable(false);
        _nsTextField19.setEnabled(true);
        _nsTextField19.setBorder(null);
        if (!(_nsBox5.getLayout() instanceof EOViewLayout)) { _nsBox5.setLayout(new EOViewLayout()); }
        _nsTextField19.setSize(67, 14);
        _nsTextField19.setLocation(18, 11);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField19, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField19);
        _nsTextField20.setSize(67, 14);
        _nsTextField20.setLocation(18, 33);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField20, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField20);
        _nsTextField21.setSize(67, 14);
        _nsTextField21.setLocation(18, 55);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField21, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField21);
        _nsTextField22.setSize(67, 14);
        _nsTextField22.setLocation(18, 77);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField22, EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField22);
        _nsTextField9.setSize(297, 14);
        _nsTextField9.setLocation(87, 11);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField9);
        _nsTextField10.setSize(297, 14);
        _nsTextField10.setLocation(87, 33);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField10);
        _nsTextField11.setSize(297, 14);
        _nsTextField11.setLocation(87, 55);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField11);
        _nsTextField4.setSize(297, 14);
        _nsTextField4.setLocation(87, 77);
        ((EOViewLayout)_nsBox5.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox5.add(_nsTextField4);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(396, 102);
        _nsBox5.setLocation(2, 15);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Properties", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField18, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField18.setEditable(false);
        _nsTextField18.setOpaque(false);
        _nsTextField18.setText("Expires:");
        _nsTextField18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField18.setSelectable(false);
        _nsTextField18.setEnabled(true);
        _nsTextField18.setBorder(null);
        _setFontForComponent(_nsTextField17, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField17.setEditable(false);
        _nsTextField17.setOpaque(false);
        _nsTextField17.setText("Created:");
        _nsTextField17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField17.setSelectable(false);
        _nsTextField17.setEnabled(true);
        _nsTextField17.setBorder(null);
        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsTextField17.setSize(49, 14);
        _nsTextField17.setLocation(36, 11);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField17, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField17);
        _nsTextField18.setSize(49, 14);
        _nsTextField18.setLocation(36, 33);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField18, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField18);
        _nsTextField6.setSize(297, 14);
        _nsTextField6.setLocation(87, 11);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField6);
        _nsTextField7.setSize(297, 14);
        _nsTextField7.setLocation(87, 33);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField7);
        _nsImageView2.setSize(16, 16);
        _nsImageView2.setLocation(14, 32);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsImageView2, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsImageView2);
        if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
        _nsBox3.setSize(396, 58);
        _nsBox3.setLocation(2, 15);
        ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
        _nsBox2.add(_nsBox3);
        _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Dates", true, "Lucida Grande", 11, Font.PLAIN));
        _setFontForComponent(_nsTextField16, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField16.setEditable(false);
        _nsTextField16.setOpaque(false);
        _nsTextField16.setText("Name:");
        _nsTextField16.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField16.setSelectable(false);
        _nsTextField16.setEnabled(true);
        _nsTextField16.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField15") == null) {
            _setFontForComponent(_nsTextField15, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField15.setEditable(false);
            _nsTextField15.setOpaque(false);
            _nsTextField15.setText("Small System Font Text");
            _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField15.setSelectable(false);
            _nsTextField15.setEnabled(true);
            _nsTextField15.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField14") == null) {
            _setFontForComponent(_nsTextField14, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField14.setEditable(false);
            _nsTextField14.setOpaque(false);
            _nsTextField14.setText("Small System Font Text");
            _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField14.setSelectable(false);
            _nsTextField14.setEnabled(true);
            _nsTextField14.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField13") == null) {
            _setFontForComponent(_nsTextField13, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField13.setEditable(false);
            _nsTextField13.setOpaque(false);
            _nsTextField13.setText("31 May 2005");
            _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField13.setSelectable(false);
            _nsTextField13.setEnabled(true);
            _nsTextField13.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField12") == null) {
            _setFontForComponent(_nsTextField12, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField12.setEditable(false);
            _nsTextField12.setOpaque(false);
            _nsTextField12.setText("31 May 2005");
            _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField12.setSelectable(false);
            _nsTextField12.setEnabled(true);
            _nsTextField12.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsButton10") == null) {
            _setFontForComponent(_nsButton10, "Lucida Grande", 11, Font.PLAIN);
            _nsButton10.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton9") == null) {
            _setFontForComponent(_nsButton9, "Lucida Grande", 10, Font.PLAIN);
            _nsButton9.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton8") == null) {
            _setFontForComponent(_nsButton8, "Lucida Grande", 10, Font.PLAIN);
            _nsButton8.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton7") == null) {
            _setFontForComponent(_nsButton7, "Lucida Grande", 10, Font.PLAIN);
            _nsButton7.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton6") == null) {
            _setFontForComponent(_nsButton6, "Lucida Grande", 11, Font.PLAIN);
            _nsButton6.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton5") == null) {
            _setFontForComponent(_nsButton5, "Lucida Grande", 10, Font.PLAIN);
            _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        }

        _eoTableColumn3.setMinWidth(38);
        _eoTableColumn3.setMaxWidth(1000);
        _eoTableColumn3.setPreferredWidth(173);
        _eoTableColumn3.setWidth(173);
        _eoTableColumn3.setResizable(true);
        _eoTableColumn3.setHeaderValue("Name");
        if ((_eoTableColumn3.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn3.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView2") == null) {
            _nsTableView2.table().addColumn(_eoTableColumn3);
            _setFontForComponent(_nsTableView2.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView2.table().setRowHeight(20);
        }

        _eoTableColumn2.setMinWidth(27);
        _eoTableColumn2.setMaxWidth(1000);
        _eoTableColumn2.setPreferredWidth(131);
        _eoTableColumn2.setWidth(131);
        _eoTableColumn2.setResizable(true);
        _eoTableColumn2.setHeaderValue("Key");
        if ((_eoTableColumn2.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn2.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }
        _eoTableColumn1.setMinWidth(40);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(40);
        _eoTableColumn1.setWidth(40);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("Name");
        if ((_eoTableColumn1.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn1.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _nsTableView1.table().addColumn(_eoTableColumn1);
            _nsTableView1.table().addColumn(_eoTableColumn2);
            _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView1.table().setRowHeight(20);
        }

        if (_replacedObjects.objectForKey("_nsTextField11") == null) {
            _setFontForComponent(_nsTextField11, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField11.setEditable(false);
            _nsTextField11.setOpaque(false);
            _nsTextField11.setText("Small System Font Text");
            _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField11.setSelectable(false);
            _nsTextField11.setEnabled(true);
            _nsTextField11.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField10") == null) {
            _setFontForComponent(_nsTextField10, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField10.setEditable(false);
            _nsTextField10.setOpaque(false);
            _nsTextField10.setText("Small System Font Text");
            _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField10.setSelectable(false);
            _nsTextField10.setEnabled(true);
            _nsTextField10.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField9") == null) {
            _setFontForComponent(_nsTextField9, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField9.setEditable(false);
            _nsTextField9.setOpaque(false);
            _nsTextField9.setText("Small System Font Text");
            _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField9.setSelectable(false);
            _nsTextField9.setEnabled(true);
            _nsTextField9.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField8") == null) {
            _setFontForComponent(_nsTextField8, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField8.setEditable(false);
            _nsTextField8.setOpaque(false);
            _nsTextField8.setText("Small System Font Text");
            _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField8.setSelectable(true);
            _nsTextField8.setEnabled(true);
            _nsTextField8.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField7") == null) {
            _setFontForComponent(_nsTextField7, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField7.setEditable(false);
            _nsTextField7.setOpaque(false);
            _nsTextField7.setText("30 May 2005");
            _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField7.setSelectable(false);
            _nsTextField7.setEnabled(true);
            _nsTextField7.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField6") == null) {
            _setFontForComponent(_nsTextField6, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField6.setEditable(false);
            _nsTextField6.setOpaque(false);
            _nsTextField6.setText("30 May 2005");
            _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField6.setSelectable(false);
            _nsTextField6.setEnabled(true);
            _nsTextField6.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField5") == null) {
            _setFontForComponent(_nsTextField5, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField5.setEditable(false);
            _nsTextField5.setOpaque(false);
            _nsTextField5.setText("Small System Font Text");
            _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField5.setSelectable(true);
            _nsTextField5.setEnabled(true);
            _nsTextField5.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField4.setEditable(false);
            _nsTextField4.setOpaque(false);
            _nsTextField4.setText("Small System Font Text");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(false);
            _nsTextField4.setEnabled(true);
            _nsTextField4.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField3.setEditable(false);
            _nsTextField3.setOpaque(false);
            _nsTextField3.setText("Small System Font Text");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(false);
            _nsTextField3.setEnabled(true);
            _nsTextField3.setBorder(null);
        }

        if (_replacedObjects.objectForKey("_nsButton4") == null) {
            _setFontForComponent(_nsButton4, "Lucida Grande", 11, Font.PLAIN);
            _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 10, Font.PLAIN);
            _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 10, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        _eoTableColumn0.setMinWidth(45);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(388);
        _eoTableColumn0.setWidth(388);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("Subkey");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(20);
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 11, Font.PLAIN);
            _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 11, Font.PLAIN);
            _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_popup0") == null) {
            _setFontForComponent(_popup0, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsButton11") == null) {
            _setFontForComponent(_nsButton11, "Lucida Grande", 11, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField2") == null) {
            _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField2.setEditable(false);
            _nsTextField2.setOpaque(false);
            _nsTextField2.setText("Small System Font Text");
            _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField2.setSelectable(true);
            _nsTextField2.setEnabled(true);
            _nsTextField2.setBorder(null);
        }

        _setFontForComponent(_nsTextField1, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Email:");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("Comment:");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(60, 14);
        _nsTextField0.setLocation(25, 55);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField0);
        _nsTextField1.setSize(60, 14);
        _nsTextField1.setLocation(25, 33);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField1);
        _nsTextField2.setSize(222, 14);
        _nsTextField2.setLocation(87, 11);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField2);
        _nsTextField8.setSize(222, 14);
        _nsTextField8.setLocation(87, 33);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField8);
        _nsTextField5.setSize(222, 14);
        _nsTextField5.setLocation(87, 55);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField5);
        _nsTextField16.setSize(60, 14);
        _nsTextField16.setLocation(25, 11);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField16, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField16);
        _nsImageView1.setSize(62, 64);
        _nsImageView1.setLocation(321, 8);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsImageView1, EOViewLayout.MinXMargin | EOViewLayout.MaxYMargin);
        _nsBox1.add(_nsImageView1);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(396, 80);
        _nsBox1.setLocation(2, 15);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("Owner", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(400, 97);
        _nsBox0.setLocation(17, 0);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsBox2.setSize(400, 75);
        _nsBox2.setLocation(17, 104);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox2);
        _nsBox4.setSize(400, 119);
        _nsBox4.setLocation(17, 183);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox4);
        _nsBox6.setSize(400, 78);
        _nsBox6.setLocation(17, 306);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox6, EOViewLayout.WidthSizable | EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox6);
        _nsButton0.setSize(123, 22);
        _nsButton0.setLocation(157, 386);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);

        if (_replacedObjects.objectForKey("_nsTabView0") == null) {
            _nsTabView0.addTab("Key", _nsView0);
            _nsTabView0.addTab("User IDs", _nsView1);
            _nsTabView0.addTab("Subkeys", _nsView2);
            _nsTabView0.addTab("Photo", _nsView3);
            _nsTabView0.setSelectedIndex(2);
        }

        if (!(_nsView4.getLayout() instanceof EOViewLayout)) { _nsView4.setLayout(new EOViewLayout()); }
        _nsTabView0.setSize(444, 457);
        _nsTabView0.setLocation(11, 7);
        ((EOViewLayout)_nsView4.getLayout()).setAutosizingMask(_nsTabView0, EOViewLayout.WidthSizable | EOViewLayout.HeightSizable);
        _nsView4.add(_nsTabView0);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView4.setSize(466, 471);
            _eoFrame0.setTitle("Window");
            _eoFrame0.setLocation(473, 207);
            _eoFrame0.setSize(466, 471);
        }
    }
}
