//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace StockQuoteClient {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class StockQuote {
        
        private string symbolField;
        
        private string companyField;
        
        private string priceField;
        
        private string timeField;
        
        private string changeField;
        
        private decimal prevCloseField;
        
        private decimal openField;
        
        private string bidField;
        
        private string askField;
        
        private decimal yearTargetField;
        
        private string dayRangeField;
        
        private string yearRangeField;
        
        private string volumeField;
        
        private string avgVolField;
        
        private string marketCapField;
        
        private decimal peField;
        
        private decimal ePSField;
        
        private string divYieldField;
        
        private string webSiteField;
        
        private string businessField;
        
        private string sicField;
        
        private string sicnameField;
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string Change {
            get {
                return this.changeField;
            }
            set {
                this.changeField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrevClose {
            get {
                return this.prevCloseField;
            }
            set {
                this.prevCloseField = value;
            }
        }
        
        /// <remarks/>
        public decimal Open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        public string Bid {
            get {
                return this.bidField;
            }
            set {
                this.bidField = value;
            }
        }
        
        /// <remarks/>
        public string Ask {
            get {
                return this.askField;
            }
            set {
                this.askField = value;
            }
        }
        
        /// <remarks/>
        public decimal YearTarget {
            get {
                return this.yearTargetField;
            }
            set {
                this.yearTargetField = value;
            }
        }
        
        /// <remarks/>
        public string DayRange {
            get {
                return this.dayRangeField;
            }
            set {
                this.dayRangeField = value;
            }
        }
        
        /// <remarks/>
        public string YearRange {
            get {
                return this.yearRangeField;
            }
            set {
                this.yearRangeField = value;
            }
        }
        
        /// <remarks/>
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <remarks/>
        public string AvgVol {
            get {
                return this.avgVolField;
            }
            set {
                this.avgVolField = value;
            }
        }
        
        /// <remarks/>
        public string MarketCap {
            get {
                return this.marketCapField;
            }
            set {
                this.marketCapField = value;
            }
        }
        
        /// <remarks/>
        public decimal PE {
            get {
                return this.peField;
            }
            set {
                this.peField = value;
            }
        }
        
        /// <remarks/>
        public decimal EPS {
            get {
                return this.ePSField;
            }
            set {
                this.ePSField = value;
            }
        }
        
        /// <remarks/>
        public string DivYield {
            get {
                return this.divYieldField;
            }
            set {
                this.divYieldField = value;
            }
        }
        
        /// <remarks/>
        public string WebSite {
            get {
                return this.webSiteField;
            }
            set {
                this.webSiteField = value;
            }
        }
        
        /// <remarks/>
        public string Business {
            get {
                return this.businessField;
            }
            set {
                this.businessField = value;
            }
        }
        
        /// <remarks/>
        public string sic {
            get {
                return this.sicField;
            }
            set {
                this.sicField = value;
            }
        }
        
        /// <remarks/>
        public string sicname {
            get {
                return this.sicnameField;
            }
            set {
                this.sicnameField = value;
            }
        }
    }
}
